services:

  ollama-auth:
    image: ghcr.io/g1ibby/ollama-auth:latest
    ports:
      - "11435:80"
    environment:
      - OLLAMA_API_KEY=your_api_key_here
    volumes:
      - ollama_models:/root/.ollama

volumes:
  ollama_models:
    driver: local
